### ISSUE TITLE
mrsdb2.exceptions.CachingError: Cache renewal overdue.

### ISSUE THREAD

**Issue by dubafurb** [Netriza/mrsdb#5]
I left my computer running overnight, and I got this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/######/Desktop/######/lib/python3.7/site-packages/mrsdb2/cache.py", line 28, in loop
    raise CachingError("Cache renewal overdue.")
mrsdb2.exceptions.CachingError: Cache renewal overdue.
```
How can I stop this?

**Comment by ItzMeWilliam** [comment]
>  left my computer running overnight
If your computer is going to sleep mode, that's the problem.

You can prevent this from happening due to using sleep mode by either setting a massive hard expire
```python
from mrsdb2.mrsdb import Connection
from mrsdb2.cache import Cache
db = Connection('./db', cache=Cache(hardexpires=99999999)
```
or by disabling cache entirely
```python
from mrsdb2.mrsdb import Connection
db = Connection('./db', cache=None)
```
